---
name: "jellyfin-plugin-mergeVersions"
guid: "f21bbed8-3a97-4d8b-88b2-48aaa65427cb"
version: "12.1.0.0"
jellyfin_version: "12.1.0"
owner: "bulderi"
nicename: "Merge Versions"
description: "Automatically groups alternate movie and episode versions."
overview: "Efficient incremental version merging for large Jellyfin libraries."
category: "General"
artifacts:
  - "Jellyfin.Plugin.MergeVersions.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net10.0"
